In [2]:
#IMPORT LIBR

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn import metrics



In [5]:
data = pd.read_csv('candy-data.csv')

X=data.iloc[ :, [3,12]].values
y=data.iloc[ : , 1].values



In [6]:
# TRAIN , TEST , SPLIT our model training with 70 %  look at test_size=0.3 30% 

X_train , X_test, y_train , y_test=train_test_split(X, y, test_size = 0.3, random_state = 32)

In [11]:
X_train

array([[ 0.      , 39.460556],
       [ 0.      , 66.574585],
       [ 0.      , 81.866257],
       [ 0.      , 32.261086],
       [ 0.      , 55.103695],
       [ 0.      , 57.21925 ],
       [ 0.      , 46.783348],
       [ 0.      , 57.11974 ],
       [ 0.      , 51.41243 ],
       [ 0.      , 76.7686  ],
       [ 0.      , 41.265511],
       [ 0.      , 27.303865],
       [ 0.      , 54.526451],
       [ 0.      , 59.863998],
       [ 0.      , 73.43499 ],
       [ 1.      , 33.43755 ],
       [ 1.      , 81.642914],
       [ 0.      , 67.037628],
       [ 1.      , 60.800701],
       [ 0.      , 45.466282],
       [ 0.      , 39.185505],
       [ 0.      , 52.825947],
       [ 0.      , 55.354046],
       [ 0.      , 45.736748],
       [ 0.      , 39.141056],
       [ 0.      , 46.296597],
       [ 1.      , 56.914547],
       [ 0.      , 45.995827],
       [ 1.      , 66.971725],
       [ 0.      , 69.483788],
       [ 0.      , 63.08514 ],
       [ 0.      , 34.722   ],
       [

In [14]:
#scaling of my data 

scaler_X= StandardScaler()

X_train=scaler_X.fit_transform(X_train)
X_test= scaler_X.transform(X_test)

In [18]:
#define the model

log_model=LogisticRegression()


# train the model
log_model.fit(X_train, y_train)

LogisticRegression()

In [20]:
# make prediction 

y_pred=log_model.predict(X_test)



array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1], dtype=int64)

In [30]:
## model evaluation
# accuracy
# confusion matrix

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))



Accuracy: 0.8076923076923077


In [29]:
## confusion matrix

conf_mat=confusion_matrix(y_test,y_pred)

conf_mat

array([[16,  0],
       [ 5,  5]], dtype=int64)